'use strict';
const $=id=>document.getElementById(id);
let token='',state={keys:[],routes:[],entries:[],audit:[],revision:0},page='overview',formRevision=0,editing=null;
const titles={overview:['كل الوصول، تحت سيطرتك.','مفاتيح مستقلة لبرامجك، وحدود واضحة لكل استخدام.'],keys:['مفتاح لكل استخدام.','حدّد من يستطيع الوصول، ومتى، وبأي ميزانية.'],routes:['طريق واحد. بدائل أذكى.','رتّب الأولويات، واترك الانتقال للحالات التي تختارها.'],usage:['كل طلب، له سجل.','راقب المحاسبة والحجوزات دون حفظ محتوى المحادثات.'],audit:['لا تغيير بلا أثر.','سجل إداري بدون أسرار أو نصوص محادثات.']};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:4}).format(Number(v||0)/1e6);
function toast(msg){$('toast').textContent=msg;$('toast').classList.remove('hidden');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').classList.add('hidden'),5000)}
async function api(path,method='GET',data){const res=await fetch('/v0/management/miftah/'+path,{method,headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:data?JSON.stringify(data):undefined,cache:'no-store',credentials:'omit',redirect:'error'});if(res.status===401){token='';if(!$('login').open)$('login').showModal();throw Error('مفتاح الإدارة غير صحيح أو انتهت الجلسة')};const v=await res.json();if(!res.ok)throw Error(v.error||'تعذر إتمام الطلب');return v}
async function refresh(){state=await api('state');$('connection').textContent='متصل · إدارة محلية';render()}
function table(headers,rows){return rows.length?'<table><thead><tr>'+headers.map(x=>'<th>'+esc(x)+'</th>').join('')+'</tr></thead><tbody>'+rows.join('')+'</tbody></table>':'<div class="empty">لا توجد بيانات بعد.<br>أنشئ مسارًا، ثم مفتاحك الأول.</div>'}
function keyRows(keys){return keys.map(k=>'<tr><td><b>'+esc(k.name)+'</b><small>'+esc(k.owner||'بدون مالك')+'</small></td><td><code>'+esc(k.preview)+'</code></td><td>'+esc(k.models.join(' · '))+'</td><td><span class="badge">'+(k.enabled?'مفعّل':'موقوف')+'</span></td><td>'+money(state.entries.filter(e=>e.key_id===k.id).reduce((s,e)=>s+e.cost,0))+'</td><td><button class="quiet" data-edit="'+esc(k.id)+'">تعديل</button><button class="quiet" data-rotate="'+esc(k.id)+'">تدوير</button></td></tr>')}
function render(){const keys=state.keys||[],entries=state.entries||[];$('activeCount').textContent=keys.filter(k=>k.enabled).length;$('spend').textContent=money(entries.reduce((s,e)=>s+e.cost,0));$('requests').textContent=entries.length;$('routeCount').textContent=state.routes.length;$('revision').textContent='Revision '+state.revision;const heads=['الاسم','المفتاح','المسارات','الحالة','مسجل / محجوز','الإجراءات'];$('recentKeys').innerHTML=table(heads,keyRows(keys.slice(-5).reverse()));const q=$('search').value.toLowerCase();$('keyTable').innerHTML=table(heads,keyRows(keys.filter(k=>(k.name+' '+k.owner).toLowerCase().includes(q))));$('routeList').innerHTML=state.routes.length?state.routes.map(r=>'<article class="route-card"><h2><code>'+esc(r.alias)+'</code></h2><p>'+r.targets.length+' موديلات · سقف الإخراج '+r.max_output+'</p><ol>'+r.targets.map((t,i)=>'<li><small>'+String(i+1).padStart(2,'0')+'</small> &nbsp; '+esc(t)+'</li>').join('')+'</ol><p>انتقال عند '+esc(r.retry_statuses.join(' / '))+'</p><button class="quiet" data-route="'+esc(r.alias)+'">تعديل وترتيب ←</button></article>').join(''):'<div class="empty">ابدأ بمسار واحد.<br>حدّد الموديل الأساسي، ثم البدائل إن رغبت.</div>';
$('usageTable').innerHTML=table(['الوقت','المفتاح','المسار / الموديل','التكلفة','الحالة','المحاولات'],entries.slice().reverse().slice(0,500).map(e=>'<tr><td>'+esc(new Date(e.at).toLocaleString('ar-SA'))+'</td><td>'+esc(keys.find(k=>k.id===e.key_id)?.name||e.key_id)+'</td><td>'+esc(e.alias)+'<small>'+esc(e.model)+'</small></td><td>'+money(e.cost)+'</td><td>'+esc(e.status)+'</td><td>'+e.attempts+'</td></tr>'));$('auditTable').innerHTML=table(['الوقت','الإجراء','المعرّف'],(state.audit||[]).slice().reverse().slice(0,500).map(e=>'<tr><td>'+esc(new Date(e.at).toLocaleString('ar-SA'))+'</td><td>'+esc(e.action)+'</td><td><code>'+esc(e.subject)+'</code></td></tr>'))}
function navigate(p){page=p;document.querySelectorAll('.page').forEach(el=>el.classList.toggle('hidden',el.id!==p));document.querySelectorAll('nav button').forEach(el=>el.classList.toggle('active',el.dataset.page===p));$('pageTitle').textContent=titles[p][0];$('pageDescription').textContent=titles[p][1]}
function keyForm(k){if(!state.routes.length){toast('أنشئ مسار موديل أولًا');navigate('routes');return};editing=k||null;formRevision=state.revision;$('keyForm').reset();$('keyHeading').textContent=k?'إعدادات المفتاح':'مفتاح افتراضي جديد';$('keyID').value=k?.id||'';$('keyName').value=k?.name||'';$('keyOwner').value=k?.owner||'';$('keyEnabled').checked=k?.enabled??true;$('keyModels').innerHTML=state.routes.map(r=>'<option value="'+esc(r.alias)+'"'+(k?.models.includes(r.alias)?' selected':'')+'>'+esc(r.alias)+'</option>').join('');if(k){for(const n of ['Total','Daily','Weekly','Monthly'])$('limit'+n).value=k.limits[n.toLowerCase()]/1e6;$('limitRPM').value=k.limits.rpm;$('limitConcurrent').value=k.limits.concurrent;$('keyExpiry').value=k.expires_at?new Date(new Date(k.expires_at).getTime()-new Date(k.expires_at).getTimezoneOffset()*60000).toISOString().slice(0,16):''};$('keyDialog').showModal()}
function showSecret(secret){$('secret').value=secret;$('secretDialog').showModal()}
function targetRow(value=''){
 const row=document.createElement('div');row.className='target';row.draggable=true;
 row.innerHTML='<span class="grip" aria-label="اسحب">⠿</span><input required dir="ltr" maxlength="200" placeholder="provider/model"><button type="button" class="quiet" data-up aria-label="رفع الأولوية">↑</button><button type="button" class="quiet" data-down aria-label="خفض الأولوية">↓</button><button type="button" class="quiet" data-remove aria-label="حذف">✕</button>';
 row.querySelector('input').value=value;
 row.addEventListener('dragstart',e=>{row.classList.add('dragging');e.dataTransfer.setData('text/plain','miftah-target');e.dataTransfer.effectAllowed='move'});
 row.addEventListener('dragend',()=>row.classList.remove('dragging'));
 row.addEventListener('dragover',e=>{e.preventDefault();const dragged=$('targetList').querySelector('.dragging');if(dragged&&dragged!==row){const rect=row.getBoundingClientRect();$('targetList').insertBefore(dragged,e.clientY>rect.top+rect.height/2?row.nextSibling:row)}});
 row.addEventListener('drop',e=>e.preventDefault());
 row.addEventListener('click',e=>{if(e.target.hasAttribute('data-up')&&row.previousElementSibling)row.previousElementSibling.before(row);if(e.target.hasAttribute('data-down')&&row.nextElementSibling)row.nextElementSibling.after(row);if(e.target.hasAttribute('data-remove'))row.remove()});$('targetList').append(row)
}
function routeForm(r){formRevision=state.revision;$('routeForm').reset();$('retryUnknown').checked=r?.retry_unknown||false;$('routeAlias').readOnly=!!r;$('routeAlias').value=r?.alias||'';$('targetList').replaceChildren();(r?.targets||['']).forEach(targetRow);if(r){$('inputPrice').value=r.input_price/1e6;$('outputPrice').value=r.output_price/1e6;$('maxOutput').value=r.max_output;document.querySelectorAll('[name=retry]').forEach(el=>el.checked=r.retry_statuses.includes(Number(el.value)))};$('routeDialog').showModal()}
let saving=false;
async function guard(fn){if(saving)return;saving=true;try{await fn()}catch(e){toast(e.message)}finally{saving=false}}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.page)navigate(b.dataset.page);if(b.dataset.close){if(b.dataset.close==='secretDialog')$('secret').value='';$(b.dataset.close).close()};if(b.dataset.edit)keyForm(state.keys.find(k=>k.id===b.dataset.edit));if(b.dataset.route)routeForm(state.routes.find(r=>r.alias===b.dataset.route));if(b.dataset.rotate&&confirm('تدوير المفتاح يبطل النص القديم فورًا. متابعة؟'))guard(async()=>{const v=await api('rotate','POST',{id:b.dataset.rotate});showSecret(v.secret);await refresh()})});
$('newKey').onclick=()=>keyForm();$('newRoute').onclick=()=>routeForm();$('refresh').onclick=()=>guard(refresh);$('search').oninput=render;$('addTarget').onclick=()=>{if($('targetList').children.length<5)targetRow();else toast('حد هذه النسخة خمسة موديلات')};
$('loginForm').onsubmit=async e=>{e.preventDefault();token=$('adminToken').value;$('adminToken').value='';try{await refresh();$('loginError').textContent='';$('login').close()}catch(err){token='';$('loginError').textContent=err.message}};
$('logout').onclick=()=>{token='';state={keys:[],routes:[],entries:[],audit:[],revision:0};render();$('connection').textContent='غير متصل';$('login').showModal()};$('login').addEventListener('cancel',e=>e.preventDefault());
$('keyForm').onsubmit=e=>{e.preventDefault();guard(async()=>{const limits={};for(const n of ['Total','Daily','Weekly','Monthly'])limits[n.toLowerCase()]=Math.round(Number($('limit'+n).value)*1e6);limits.rpm=Number($('limitRPM').value);limits.concurrent=Number($('limitConcurrent').value);const k={...(editing||{}),name:$('keyName').value,owner:$('keyOwner').value,enabled:$('keyEnabled').checked,models:[...$('keyModels').selectedOptions].map(o=>o.value),limits,expires_at:$('keyExpiry').value?new Date($('keyExpiry').value).toISOString():''};if(editing)await api('keys','PUT',{key:k,revision:formRevision});else{const v=await api('keys','POST',k);showSecret(v.secret)};$('keyDialog').close();await refresh();toast('تم حفظ المفتاح')})};
const unknownLabel=document.createElement('label');unknownLabel.className='check';unknownLabel.innerHTML='<input type="checkbox" id="retryUnknown"> أخطاء غير مصنّفة — قد تعيد طلبًا بتكلفة مكررة';$('routeForm').querySelector('fieldset').append(unknownLabel);
$('routeForm').onsubmit=e=>{e.preventDefault();guard(async()=>{const route={alias:$('routeAlias').value.trim(),targets:[...$('targetList').querySelectorAll('input')].map(x=>x.value.trim()),retry_statuses:[...document.querySelectorAll('[name=retry]:checked')].map(x=>Number(x.value)),retry_unknown:$('retryUnknown').checked,input_price:Math.round(Number($('inputPrice').value)*1e6),output_price:Math.round(Number($('outputPrice').value)*1e6),max_output:Number($('maxOutput').value)};await api('routes','PUT',{route,revision:formRevision});$('routeDialog').close();await refresh();toast('تم حفظ ترتيب المسار')})};
$('copySecret').onclick=()=>guard(async()=>{await navigator.clipboard.writeText($('secret').value);toast('تم النسخ؛ احفظه في مدير كلمات المرور')});$('secretDialog').addEventListener('close',()=>{$('secret').value=''});$('exportUsage').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(state.entries,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='miftah-usage.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
$('login').showModal();
